### ISSUE TITLE
Reader SDK Details For Non Us Residents

### ISSUE THREAD

**Issue by mattjamesaus** [square/reader-sdk-android-quickstart#13]
Is there a particular contact at square we can reach out to if we're integrating with the square reader SDK for our internationalised app but based in another country e.g Australia? 

Essentially after some SDK details so we can do some testing for our US clients.

**Comment by StephenJosey** [comment]
This is quite a popular request, and we would love for it to be available to non-US countries, but unfortunately it does take time. There is currently no ETA on when it will be released for other countries. Currently there's no way to integrate ReaderSDK while outside the United States.

**Comment by StephenJosey** [comment]
Hi @legomanaustralia are you still interested in this? If so, could you please reach out to our API Support to see if we'd be able to help you further: https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68

Please reference this GitHub issue in the support ticket.
