### ISSUE TITLE
Square Reader shows message "Connecting to reader" even when reader is connected. 

### ISSUE THREAD

**Issue by krishnakapil** [square/reader-sdk-android-quickstart#15]
When app is not used for few minutes, the square reader shows error "Connecting to reader" message. This started happening from yesterday. Only way to fix this is kill and restart the app.

**Comment by StephenJosey** [comment]
Hi @krishnakapil sorry for the delay in response. Since it's been awhile, could you try with the latest Android Reader SDK version (1.3.1) and let me know if you continue to experience the same issue?
