### ISSUE TITLE
Reader SDK card_transaction_already_in_progress

### ISSUE THREAD

**Issue by krishnakapil** [square/reader-sdk-android-quickstart#17]
I am getting this error when launching checkout. 

**card_transaction_already_in_progress** 

A checkout operation is already in progress and a card has been presented for payment. Ensure that the in-progress checkout is complete before calling CheckoutManager#startCheckoutActivity again.

What am i doing wrong? How do i check if any payment is in progress? I am making sure to launch checkout only once and still keep getting this error.

**Comment by StephenJosey** [comment]
Hi @krishnakapil sorry for the delay. If you're still experiencing this issue could you provide a code snippet or repo where this issue is occurring? Does it happen every time, or only after the first time, or after X time?

**Comment by StephenJosey** [comment]
Closing due to no response.
