### ISSUE TITLE
Configurations for Android Product Flavors

### ISSUE THREAD

**Issue by dibelogrivaya** [square/reader-sdk-android-quickstart#20]
Hi!
It would be great if there was an example of how to use SDK with different credentials for different product flavors.

The application can be styled and configured for different clients. For iOS I use for this different targets in Xcode and, accordingly, different frameworks. For Android - productFlavors, but I can't figure out, how to set up different SDK credentials for different productFlavors. 

```
productFlavors {
        app1 {}
        app2 {}
    }

maven {
            url "https://sdk.squareup.com/android"
            credentials {
                username SQUARE_READER_SDK_APPLICATION_ID
                password SQUARE_READER_SDK_REPOSITORY_PASSWORD
            }
        }

```

**Comment by StephenJosey** [comment]
See this issue around product flavors: https://github.com/square/react-native-square-reader-sdk/issues/69

Please let me know if that doesn't work for you.

**Comment by StephenJosey** [comment]
Closing this, as the referenced issue above was resolved. Please comment if you continue having this issue or have other concerns. Thanks!
