### ISSUE TITLE
Signature during checkout doesn't seem to work

### ISSUE THREAD

**Issue by davenotdavid** [square/reader-sdk-android-quickstart#23]
With/without a Square Reader device (contactless/chip and magstripe) on-hand, I was wondering how to get signature collections to work during the checkout process. Or, are signatures only intended for transactions done with card swipes via Square Readers?

I've set the boolean flag to true (`params.collectSignature(true);`) prior to launching a cash transaction (and manual card entries, but to no avail as mentioned in [this issue](https://github.com/square/reader-sdk-android-quickstart/issues/22)) with the following code:

```
private void startCheckout(Money checkoutAmount) {
    if (waitingForActivityStart) {
      return;
    }
    waitingForActivityStart = true;

    CheckoutManager checkoutManager = ReaderSdk.checkoutManager();
    CheckoutParameters.Builder params = CheckoutParameters.newBuilder(checkoutAmount);
    // TODO: Signatures still don't seem to be shown even with the following
    params.collectSignature(true);
    Set<AdditionalPaymentType> payments = new HashSet<>();
    payments.add(AdditionalPaymentType.MANUAL_CARD_ENTRY);
    payments.add(AdditionalPaymentType.CASH);
    payments.add(AdditionalPaymentType.OTHER);
    params.additionalPaymentTypes(payments);
    params.note("Testing note...");
    checkoutManager.startCheckoutActivity(this, params.build());
}
```

... where it just takes me directly straight to the "Transaction Complete" screen instead:
![Screenshot_20200123-115313](https://user-images.githubusercontent.com/25012364/73186165-4ce93480-40ed-11ea-85a2-67f0d05fce72.png)

**Comment by StephenJosey** [comment]
Hey @DaveNOTDavid there will never be a signature required for cash transactions or manual card entry (manual card entry sort of implies the card isn't present, which implies the person might not be present). There should be a signature that will be asked when using contactless/insert/swipe cards though (card-present). Let me know if that's not the case.
