### ISSUE TITLE
Could not find Reader SDK from Maven for a Square account

### ISSUE THREAD

**Issue by davenotdavid** [square/reader-sdk-android-quickstart#27]
Not sure where to ask this question, so I'll try here for starters.

After [following the steps (particularly steps 1-2) for installing the Reader SDK for Android from the docs](https://developer.squareup.com/docs/reader-sdk/build-on-android), we noticed a strange issue with retrieving the dependencies from Maven. We have two Square accounts (one for the dev environment, and the other for prod) that are both set to "Production Settings" instead of sandbox, neither account is activated, and only one of our Square accounts' (our "prod" one in this case) Reader SDK credentials work for getting the Reader SDK dependency. Why is it that our other account's application ID and repository password can't get us the proper `aar` for the Reader SDK? **Note that we get the same failed results even in this `reader-sdk-android-quickstart` project after plugging in the creds into the `gradle.properties` file.**

Here's the build failure when trying to sync with Gradle:
![image](https://user-images.githubusercontent.com/25012364/79162159-c6b6c300-7daa-11ea-8c06-fcb6d71a570e.png)

Here's the failure when running the task locally (in which we're wondering why a `jar` file is trying to be retrieved when Maven only has `aar` and `pom` files in the SDK's maven repo even though our "prod" one works despite not having a `jar` file as well?):
```
./gradlew app:androidDependencies
Parallel execution is an incubating feature.

> Configure project :app

...

> Task :app:androidDependencies
debug

> Task :app:androidDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:androidDependencies'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg.jar (com.squareup.sdk.reader:reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg:1.3.6).
     Searched in the following locations:
         https://sdk.squareup.com/android/com/squareup/sdk/reader/reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg/1.3.6/reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg-1.3.6.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
1 actionable task: 1 executed

```

Here's the maven repo for the SDK pointing to our "dev" environment, and does this look right to you?:
![image](https://user-images.githubusercontent.com/25012364/79229792-982ffb00-7e31-11ea-915a-d2d3d787d91d.png)
![image](https://user-images.githubusercontent.com/25012364/79229711-7cc4f000-7e31-11ea-98ee-3b2b9e36087f.png)

**Comment by StephenJosey** [comment]
As you already pointed out, the issue seems to be due to the fact that Gradle is trying to download a jar file, while instead it should be searching for an aar file. As you’ve mentioned, the aar is present in the repo, which is correct.
Can you please share the contents of the `reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg-1.3.6.pom` file (the one from your last screenshot). It should contain a line `<packaging>aar</packaging>`.

Also, we’ve noticed that you’re using an old version of Gradle - 4.10.1, which might or might not be the issue. In the quickstart we’re using 5.1.1, which is still old, compared to recent 6.3 release. Try bumping the Gradle version and see if it helps as well.

**Comment by davenotdavid** [comment]
@StephenJosey - Thank you for the response. Here's the `reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg-1.3.6.pom` file (with the corresponding `aar` packaging tag shown below):

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <name>reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg</name>
  <groupId>com.squareup.sdk.reader</groupId>
  <artifactId>reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg</artifactId>
  <version>1.3.6</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.squareup.sdk.reader</groupId>
      <artifactId>reader-sdk-14d6ee3f</artifactId>
      <version>1.3.6</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**... so it turns out that bumping up Gradle's version (to v5.1.1) finally worked locally on my machine for the Gradle build and `app:androidDependencies` task, but for some reason is still failing on our CI builds with the same errors as mentioned earlier**:
```
> Task :app:androidDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:androidDependencies'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg.jar (com.squareup.sdk.reader:reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg:1.3.6).
     Searched in the following locations:
         https://sdk.squareup.com/android/com/squareup/sdk/reader/reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg/1.3.6/reader-sdk-sq0idp-T4SClu2rWV2AcYcEiHALXg-1.3.6.jar
```

**Comment by StephenJosey** [comment]
Hm, interesting, thanks for confirming. Is your CI machine running a different Gradle version as well? To be clear, it seems like the issue is something with Gradle, as we're correctly providing an `aar` file, which should be all it needs, so I'm not completely clear what's going wrong (seems to be outside of Square's scope).

**Comment by davenotdavid** [comment]
@StephenJosey - yeah, there's definitely something fishy going on our end with CI we're gonna have to figure out. Thanks for this though 👍
