### ISSUE TITLE
Immersive (full screen) mode for checkoutManager.startCheckoutActivity

### ISSUE THREAD

**Issue by iklochko** [square/reader-sdk-android-quickstart#3]
Hello.
I'm using the SDK in the app working in Immersive mode. On full screen activity I call:
```
checkoutManager.startCheckoutActivity(this, params.build());
```
Checkout activity appears with notification bar and other android controls shown.
Is there a way to start checkout activity fullscreen also?
I use currently latest version of reader sdk, 1.0.4.

**Comment by StephenJosey** [comment]
Unfortunately, there's currently no way to hide the notification bar when calling the Reader SDK checkout.
