### ISSUE TITLE
how can i change country for Squareup profile?

### ISSUE THREAD

**Issue by imran-samed** [square/reader-sdk-android-quickstart#4]
My country is not listed in Reader SDK accessible list.
so is there any way, i can change my country in profile.

**Comment by StephenJosey** [comment]
You cannot change your country in your account. You would need to create an entirely new account and select a different country. With that said, it still will not allow you to take card payments with ReaderSDK, as it will check what country you are currently in, and if you're outside of the country associated with your account the transaction will fail.

https://squareup.com/help/us/en/article/5415-can-i-accept-multiple-currencies-with-square
https://squareup.com/help/us/en/article/4956-international-availability
