### ISSUE TITLE
Androidx support for Reader SDK

### ISSUE THREAD

**Issue by krishnakapil** [square/reader-sdk-android-quickstart#5]
I am unable to use androidx with square reader sdk. I see that square is still using old support libraries. Is this change going to happen soon?

**Comment by krishnakapil** [comment]
When i change my my app to use androidx, app is crashing since square doesn't support it. Is there a way to overcome this issue?

**Comment by pyricau** [comment]
@krishnakapil if you have enabled androidx with `android.useAndroidX=true`, then you'll need the add `android.enableJetifier=true` next to it.

See https://developer.android.com/jetpack/androidx/migrate
