### ISSUE TITLE
Maintain Separate SDK's for debug and release

### ISSUE THREAD

**Issue by krishnakapil** [square/reader-sdk-android-quickstart#8]
I want to be able to use development and production sdk for debug and release. I was unable to get it to work since the dependency is based on the square application id and even has different credentials for development and production.

Can someone give me an example on how i differentiate them in gradle.

**Comment by StephenJosey** [comment]
If you're asking how to use sandbox and production with ReaderSDK, then unfortunately at this time ReaderSDK doesn't support sandbox (only production).
